# Generated by Django 4.1.2 on 2023-06-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='metodo_pago',
            field=models.ForeignKey(db_column='idPago', on_delete=django.db.models.deletion.CASCADE, to='Tienda.pago'),
        ),
    ]
