# Generated by Django 4.1.2 on 2023-06-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='metodo_pago',
            new_name='form_payment_card',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='metodo_pago',
            new_name='form_payment_card',
        ),
    ]
