# Generated by Django 4.1.4 on 2023-06-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('nombre_pago', models.CharField(max_length=30)),
                ('metodo_pago', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('descripcion_producto', models.CharField(max_length=350)),
                ('precio_producto', models.IntegerField()),
                ('imagen_producto', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Detalleproducto',
            fields=[
                ('id_detalle', models.AutoField(db_column='idDetalle', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('id_producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='usuarios.producto')),
                ('id_usuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
