# Generated by Django 4.1.2 on 2023-06-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_nacimiento',
            new_name='form_birthday',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='form_correo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='direccion',
            new_name='form_direction',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='form_password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='form_user',
        ),
    ]
