# Generated by Django 4.1.2 on 2023-06-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_pago_nombre_pago_pago_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('mastercard', 'Mastercard'), ('visa', 'Visa'), ('amex', 'American Express')], max_length=20),
        ),
    ]
